openapi: 3.0.1

info:
  title: FastAPI
  version: 0.1.0

servers:
  - url: http://localhost:83/

paths:
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /forecast/{geohash}:
    get:
      summary: Forecast
      description: |-
        function returns a forecast for a given geohash

        geohash - string of a geohash, must correspond to a geohash present in redis
      operationId: forecast_forecast__geohash__get
      parameters:
        - name: geohash
          in: path
          required: true
          schema:
            title: Geohash
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
  /rawdata/{timestamp}:
    get:
      summary: Rawdata
      description: |-
        function returns all raw data from  timestamp up until now
        timestamp - unix timestamp in miliseconds, defaults to 1 hour
      operationId: rawdata_rawdata__timestamp__get
      parameters:
        - name: timestamp
          in: path
          required: true
          schema:
            title: Timestamp
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
  /update/{state}/{model_name}:
    post:
      summary: Update Model
      description: |-
        function returns all raw data from  timestamp up until now
        timestamp - unix timestamp in miliseconds, defaults to 1 hour
      operationId: update_model_update__state___model_name__post
      parameters:
        - name: state
          in: path
          required: true
          schema:
            type: string
            title: State
        - name: model_name
          in: path
          required: true
          schema:
            type: string
            title: Model Name
        - name: req_api_key
          in: query
          required: true
          schema:
            type: string
            title: Req Api Key
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/Body_update_model_update__state___model_name__post"
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
components:
  schemas:
    Body_update_model_update__state___model_name__post:
      properties:
        file:
          type: string
          format: binary
          title: File
      type: object
      required:
        - file
      title: Body_update_model_update__state___model_name__post
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
