openapi: 3.0.3
info:
  title: FastAPI
  version: 0.1.0

servers:
  - url: http://localhost:83/

paths:
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
  /forecast/{lat}/{lon}:
    get:
      summary: Forecast
      description: |-
        function returns a forecast for a given geohash

        geohash - string of a geohash, must correspond to a geohash present in redis
      operationId: forecast_forecast__lat___lon__get
      parameters:
        - name: lat
          in: path
          required: true
          schema:
            type: number
            title: Lat
        - name: lon
          in: path
          required: true
          schema:
            type: number
            title: Lon
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
components:
  schemas:
    Item:
      type: object
      required:
        - title
      properties:
        title:
          type: array
          items:
            type: number
            example: [12.1, 1, 14]

    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError

    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
